group_5_from_code:
  1: งบบุคลากร
  2: งบดำเนินงาน
  3: งบลงทุน
  4: งบเงินอุดหนุน
  5: งบรายจ่ายอื่น
rows:
- objc_code: 100
  objc_code_5g: 1
  objc_5: งบบุคลากร
  sub_objc: 100
  objc_8: เงินเดือน ค่าจ่างประจำ
  obj_12: เงินเดือน
- objc_code: 210
  objc_code_5g: 1
  objc_5: งบบุคลากร
  sub_objc: 210
  objc_8: เงินเดือน ค่าจ่างประจำ
  obj_12: ค่าจ้างประจำ
- objc_code: 220
  objc_code_5g: 1
  objc_5: งบบุคลากร
  sub_objc: 220
  objc_8: ค่าจ้างชั่วคราว
  obj_12: ค่าจ้างชั่วคราว
- objc_code: 230
  objc_code_5g: 1
  objc_5: งบบุคลากร
  sub_objc: 230
  objc_8: ค่าจ้างชั่วคราว
  obj_12: ค่าตอบแทนพนักงานราชการ
- objc_code: 300
  objc_code_5g: 2
  objc_5: งบดำเนินงาน
  sub_objc: 300
  objc_8: ค่าตอบแทนใช้สอยและวัสดุ
  obj_12: ค่าตอบแทน
- objc_code: 400
  objc_code_5g: 2
  objc_5: งบดำเนินงาน
  sub_objc: 400
  objc_8: ค่าตอบแทนใช้สอยและวัสดุ
  obj_12: ค่าใช้สอย
- objc_code: 410
  objc_code_5g: 2
  objc_5: งบดำเนินงาน
  sub_objc: 410
  objc_8: ค่าสาธารณูปโภค
  obj_12: ค่าสาธารณูปโภค
- objc_code: 500
  objc_code_5g: 2
  objc_5: งบดำเนินงาน
  sub_objc: 500
  objc_8: ค่าตอบแทนใช้สอยและวัสดุ
  obj_12: ค่าวัสดุ
- objc_code: 600
  objc_code_5g: 3
  objc_5: งบลงทุน
  sub_objc: 600
  objc_8: ค่าครุภัณฑ์ ที่ดิน และสิ่งก่อสร้าง
  obj_12: ค่าครุภัณฑ์
- objc_code: 700
  objc_code_5g: 3
  objc_5: งบลงทุน
  sub_objc: 700
  objc_8: ค่าครุภัณฑ์ ที่ดิน และสิ่งก่อสร้าง
  obj_12: ที่ดิน และสิ่งก่อสร้าง
- objc_code: 800
  objc_code_5g: 4
  objc_5: งบเงินอุดหนุน
  sub_objc: 800
  objc_8: เงินอุดหนุน
  obj_12: เงินอุดหนุน
- objc_code: 900
  objc_code_5g: 5
  objc_5: งบรายจ่ายอื่น
  sub_objc: 900
  objc_8: รายจ่ายอื่น
  obj_12: null
lookup_by_objc8:
  เงินเดือน ค่าจ่างประจำ:
    objc_code: 210
    obj_12: ค่าจ้างประจำ
    objc_code_5g: 1
    objc_5: งบบุคลากร
  ค่าจ้างชั่วคราว:
    objc_code: 230
    obj_12: ค่าตอบแทนพนักงานราชการ
    objc_code_5g: 1
    objc_5: งบบุคลากร
  ค่าตอบแทนใช้สอยและวัสดุ:
    objc_code: 500
    obj_12: ค่าวัสดุ
    objc_code_5g: 2
    objc_5: งบดำเนินงาน
  ค่าสาธารณูปโภค:
    objc_code: 410
    obj_12: ค่าสาธารณูปโภค
    objc_code_5g: 2
    objc_5: งบดำเนินงาน
  ค่าครุภัณฑ์ ที่ดิน และสิ่งก่อสร้าง:
    objc_code: 700
    obj_12: ที่ดิน และสิ่งก่อสร้าง
    objc_code_5g: 3
    objc_5: งบลงทุน
  เงินอุดหนุน:
    objc_code: 800
    obj_12: เงินอุดหนุน
    objc_code_5g: 4
    objc_5: งบเงินอุดหนุน
  รายจ่ายอื่น:
    objc_code: 900
    obj_12: null
    objc_code_5g: 5
    objc_5: งบรายจ่ายอื่น
lookup_by_objc5:
  งบบุคลากร: 1
  งบดำเนินงาน: 2
  งบลงทุน: 3
  งบเงินอุดหนุน: 4
  งบรายจ่ายอื่น: 5
